# Change these first
owner: davelevine # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Bookstack
    url: https://www.levine.xyz
  - name: Code-Server
    url: https://wired.io
  - name: Knowledge
    url: https://www.levine.org
  - name: Resume
    url: https://www.davidlevine.com
  - name: Search
    url: https://search.cc
    expectedStatusCodes:
      - 521
  - name: Status
    url: https://www.status.cc
  - name: Technicality
    url: https://www.technicality.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: eighty.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Dave's Status Page"
  introMessage: Service status for Dave's homelab.
  theme: night
  navbar:
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
